#!/usr/bin/env ruby

require 'tempfile'


def run_plist_buddy(*args)
  system('/usr/libexec/PlistBuddy', *args)
end

if ARGV.include?('-h')
  $stderr.puts 'plistguy, wrapper around PlistBuddy to support shell pipes as input'
  $stderr.puts '   so now you can write `cat some.plist | plistguy -c "Print :0"` and it works.'
  $stderr.puts
  $stderr.puts 'Original help for PlistBuddy:'
  run_plist_buddy('-h')
  exit
end


last = ARGV.last
if File.exists?(last)
  exit run_plist_buddy(*ARGV)
else
  lines = STDIN.readlines.join("\n")

  file = Tempfile.new('plistguy_temp')
  file.write(lines)
  file.close

  result = run_plist_buddy(*ARGV, file.path)

  File.unlink file

  exit result
end
